default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gitshoes_development

test:
  <<: *default
  database: gitshoes_test

production:
  database: gitshoes_production
  url: <%= ENV["DATABASE_URL"] %>
