User.create!([
  {email: "patrick.whitrock@flatironschool.com", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, provider: "github", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Pat Whitrock", github_login: "pat-whitrock", image: "https://avatars.githubusercontent.com/u/4731177?"}
])
Repo.create!([
  {address: "https://github.com/pat-whitrock/gitshoes", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Gitshoes", description: "", language: "JavaScript", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/gitshoes"},
  {address: "https://github.com/TSiege/gem-it", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Gem It", description: "A ruby gem maker that will make any part of a website into a gem.", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "TSiege/gem-it"},
  {address: "https://github.com/pat-whitrock/Rubydex", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Rubydex", description: "A ruby gem that works as a pokedex of the classic 151 pokemon.", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/Rubydex"},
  {address: "https://github.com/pat-whitrock/melodigest", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Melodigest", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/melodigest"},
  {address: "https://github.com/pat-whitrock/towers-of-hanoi-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Towers Of Hanoi Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/towers-of-hanoi-ruby-004"},
  {address: "https://github.com/pat-whitrock/morse-code", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Morse Code", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/morse-code"},
  {address: "https://github.com/pat-whitrock/queues-and-stacks-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Queues And Stacks Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/queues-and-stacks-ruby-004"},
  {address: "https://github.com/pat-whitrock/linked-lists-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Linked Lists Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/linked-lists-ruby-004"},
  {address: "https://github.com/flatiron-school-students/maze-solver-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Maze Solver Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "flatiron-school-students/maze-solver-ruby-004"},
  {address: "https://github.com/pat-whitrock/binary-search-tree-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Binary Search Tree Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/binary-search-tree-ruby-004"},
  {address: "https://github.com/pat-whitrock/flatiron-kitchen-ruby-004", token: "5d1e586d1d6bf4a600970b4d3d040c8589a888cd", name: "Flatiron Kitchen Ruby 004", description: "", language: "Ruby", open_issue_count: nil, github_created_at: nil, github_updated_at: nil, full_name: "pat-whitrock/flatiron-kitchen-ruby-004"}
])
UserRepo.create!([
  {user_id: 1, repo_id: 1},
  {user_id: 1, repo_id: 2},
  {user_id: 1, repo_id: 3},
  {user_id: 1, repo_id: 4},
  {user_id: 1, repo_id: 5},
  {user_id: 1, repo_id: 6},
  {user_id: 1, repo_id: 7},
  {user_id: 1, repo_id: 8},
  {user_id: 1, repo_id: 9},
  {user_id: 1, repo_id: 10},
  {user_id: 1, repo_id: 11}
])
Widget.create!([
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 1, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 2, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 3, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 4, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 5, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 6, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 7, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 8, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 9, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 10, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"},
  {color: "#357ebd", tab_font_color: "#ffffff", body_font_color: "#333333", background_color: nil, tab_font: "sans-serif", tab_font_size: "16px", tab_text: "Feedback", tab_width: "100px", tab_height: "35px", tab_edge_radius: "5px", field_font: "sans-serif", field_font_size: "14px", title_field_text: "Title", description_field_text: "Description", button_font: "sans-serif", button_font_size: "18px", button_text: "Add Issue", form_width: "300px", form_border_thickness: "1px", form_border_type: "solid", form_border_color: "#9a9a9a", form_border_radius: "5px", orientation: "right", offset: "30px", repo_id: 11, position: "fixed", edge: "bottom", tab_background_color: "#357ebd", body_font_size: "14px", body_font: "'Open Sans', sans-serif", tab_text_align: "center", tab_margin: "0px", tab_padding: "3px 10px 3px 10px", tab_line_height: "30px", tab_cursor: "pointer", tab_display: "inline-block", button_success_text: "Thank you!", button_color: "#ffffff", button_background_color: "#357ebd", form_background_color: "#ffffff"}
])
